# Use postgres/example user/password credentials

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
    ports:
      - 5432:5432
    volumes:
      - .db_data:/var/lib/postgresql/
      
volumes:
  db_data: